#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

PROG="/usr/bin/Passwall_watchdog.sh"
PID_FILE="/tmp/passwall_watchdog.pid"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" boot
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    [ -f "$PID_FILE" ] && kill -9 "$(cat "$PID_FILE")" 2>/dev/null
    rm -f "$PID_FILE"
}
